# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cpu_and_memory.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RoundProcessBar
import SpiralProgressBar

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(777, 721)
        Form.setStyleSheet("#Form{\n"
"    background-color: #A0B9D0;\n"
"    color: #3d5673;\n"
"}\n"
"#label{\n"
"    color: #3d5673;\n"
"    padding-left: 15px;\n"
"    padding-bottom:10px;\n"
"}\n"
"QLabel{\n"
"    color: #3B3561;\n"
"}    \n"
"#scrollArea{\n"
"    padding:5px;\n"
"    background-color: #A0B9D0;\n"
"    border-radius: 15px;\n"
"    color: #3d5673;\n"
"    border: 1px solid #3d5673;\n"
"}\n"
"\n"
"#scrollAreaWidgetContents{\n"
"    background-color: #A0B9D0;\n"
"    border-radius:10px;\n"
"    \n"
"    color: #3d5673;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:3px;\n"
"    padding-bottom:3px;\n"
"    padding-right:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3E8989;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-right: 5px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"/*Horizontal scrollbar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    padding-top: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3E8989;\n"
"    min-width: 20px;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -58, 727, 697))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(-1, 50, -1, 50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_cpu_main_core = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_cpu_main_core.setFont(font)
        self.txt_cpu_main_core.setStyleSheet("padding-left:15px;")
        self.txt_cpu_main_core.setObjectName("txt_cpu_main_core")
        self.gridLayout.addWidget(self.txt_cpu_main_core, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.txt_cpu_temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_cpu_temp.setFont(font)
        self.txt_cpu_temp.setStyleSheet("padding-left:15px;")
        self.txt_cpu_temp.setObjectName("txt_cpu_temp")
        self.gridLayout.addWidget(self.txt_cpu_temp, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txt_cpu_count = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_cpu_count.setFont(font)
        self.txt_cpu_count.setStyleSheet("padding-left:15px;")
        self.txt_cpu_count.setObjectName("txt_cpu_count")
        self.gridLayout.addWidget(self.txt_cpu_count, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txt_cpu_per = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_cpu_per.setFont(font)
        self.txt_cpu_per.setStyleSheet("padding-left:15px;")
        self.txt_cpu_per.setObjectName("txt_cpu_per")
        self.gridLayout.addWidget(self.txt_cpu_per, 1, 2, 1, 1)
        self.cpu_percentage = RoundProcessBar.roundProgressBar(self.widget_2)
        self.cpu_percentage.setMaximumSize(QtCore.QSize(200, 200))
        self.cpu_percentage.setObjectName("cpu_percentage")
        self.gridLayout.addWidget(self.cpu_percentage, 0, 3, 4, 1)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 15)
        self.gridLayout_2.setSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_ram_usage = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_ram_usage.setFont(font)
        self.txt_ram_usage.setStyleSheet("padding-left:15px;")
        self.txt_ram_usage.setObjectName("txt_ram_usage")
        self.gridLayout_2.addWidget(self.txt_ram_usage, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.txt_total_ram = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_total_ram.setFont(font)
        self.txt_total_ram.setStyleSheet("padding-left:15px;")
        self.txt_total_ram.setObjectName("txt_total_ram")
        self.gridLayout_2.addWidget(self.txt_total_ram, 1, 1, 1, 1)
        self.txt_used_ram = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_used_ram.setFont(font)
        self.txt_used_ram.setStyleSheet("padding-left:15px;\n"
"border-radius: 8px;\n"
"border: 1px solid rgb(105,145,181)\n"
"")
        self.txt_used_ram.setObjectName("txt_used_ram")
        self.gridLayout_2.addWidget(self.txt_used_ram, 3, 1, 1, 1)
        self.txt_available_ram = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_available_ram.setFont(font)
        self.txt_available_ram.setStyleSheet("padding-left:15px;\n"
"border-radius: 8px;\n"
"border: 1px solid rgb(41,122,110)")
        self.txt_available_ram.setObjectName("txt_available_ram")
        self.gridLayout_2.addWidget(self.txt_available_ram, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.cpu_ram = SpiralProgressBar.spiralProgressBar(self.widget_4)
        self.cpu_ram.setMaximumSize(QtCore.QSize(200, 200))
        self.cpu_ram.setObjectName("cpu_ram")
        self.gridLayout_2.addWidget(self.cpu_ram, 1, 2, 4, 1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_used_swap = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_used_swap.setFont(font)
        self.txt_used_swap.setStyleSheet("padding-left:15px;")
        self.txt_used_swap.setObjectName("txt_used_swap")
        self.gridLayout_3.addWidget(self.txt_used_swap, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.txt_free_swap = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_free_swap.setFont(font)
        self.txt_free_swap.setStyleSheet("padding-left:15px;")
        self.txt_free_swap.setObjectName("txt_free_swap")
        self.gridLayout_3.addWidget(self.txt_free_swap, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.txt_total_swap = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_total_swap.setFont(font)
        self.txt_total_swap.setStyleSheet("padding-left:15px;")
        self.txt_total_swap.setObjectName("txt_total_swap")
        self.gridLayout_3.addWidget(self.txt_total_swap, 1, 1, 1, 1)
        self.swap = QtWidgets.QWidget(self.frame_6)
        self.swap.setMaximumSize(QtCore.QSize(200, 200))
        self.swap.setObjectName("swap")
        self.gridLayout_3.addWidget(self.swap, 1, 2, 3, 1)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "System Memory"))
        self.txt_cpu_main_core.setText(_translate("Form", "N/A"))
        self.label_4.setText(_translate("Form", "CPU Percentage"))
        self.txt_cpu_temp.setText(_translate("Form", "N/A"))
        self.label_8.setText(_translate("Form", "CPU Main Core"))
        self.label_2.setText(_translate("Form", "CPU Count"))
        self.txt_cpu_count.setText(_translate("Form", "N/A"))
        self.label_6.setText(_translate("Form", "CPU Temperateure"))
        self.txt_cpu_per.setText(_translate("Form", "N/A"))
        self.txt_ram_usage.setText(_translate("Form", "N/A"))
        self.label_7.setText(_translate("Form", "Available RAM"))
        self.label_9.setText(_translate("Form", "Used RAM"))
        self.txt_total_ram.setText(_translate("Form", "N/A"))
        self.txt_used_ram.setText(_translate("Form", "N/A"))
        self.txt_available_ram.setText(_translate("Form", "N/A"))
        self.label_5.setText(_translate("Form", "Total RAM"))
        self.label_15.setText(_translate("Form", "RAM Usage"))
        self.txt_used_swap.setText(_translate("Form", "N/A"))
        self.label_20.setText(_translate("Form", "Free SWAP"))
        self.txt_free_swap.setText(_translate("Form", "N/A"))
        self.label_18.setText(_translate("Form", "Total SWAP"))
        self.label_19.setText(_translate("Form", "Used SWAP"))
        self.txt_total_swap.setText(_translate("Form", "N/A"))
# from PySide2extn.RoundProgressBar import roundProgressBar
# from PySide2extn.SpiralProgressBar import spiralProgressBar
from static import res_rc
