# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\network.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 593)
        Form.setStyleSheet("#Form{\n"
"    background-color: #A0B9D0;\n"
"}\n"
"#scrollArea{\n"
"    border:none;\n"
"}\n"
"#scrollAreaWidgetContents{\n"
"    background-color: #A0B9D0;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    background-color: #A0B9D0;\n"
"    border:none;\n"
"    \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-left:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3E8989;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-left: 15px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QPushButton{\n"
"    width:100px;\n"
"    height:33px;\n"
"    text-align: center;\n"
"    padding: 3px;\n"
"    font-weight:bold;\n"
"    border-radius:10px;\n"
"    color: #3d5673;\n"
"    border: 1px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    background-color:#78A0BC;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(10, 15, 10, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 563))
        self.scrollAreaWidgetContents.setStyleSheet("QLabel{\n"
"    color:#3B3561;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setContentsMargins(10, 20, 10, 50)
        self.verticalLayout_10.setSpacing(30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(15)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(673, 350))
        self.frame.setStyleSheet("border: none\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setStyleSheet("#widget{\n"
"        border: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_button = QtWidgets.QPushButton(self.widget)
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        self.list_servers_button = QtWidgets.QPushButton(self.widget)
        self.list_servers_button.setObjectName("list_servers_button")
        self.horizontalLayout.addWidget(self.list_servers_button)
        self.ping_button = QtWidgets.QPushButton(self.widget)
        self.ping_button.setObjectName("ping_button")
        self.horizontalLayout.addWidget(self.ping_button)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.result_text_browser = QtWidgets.QTextBrowser(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.result_text_browser.setFont(font)
        self.result_text_browser.setStyleSheet("QTextBrowser{\n"
"    border-radius: 15px;\n"
"    border: 1px solid #3d5673;\n"
"    background-color: #A0B9D0;\n"
"    padding:20px;\n"
"    gridline-color: #3d5673;\n"
"    color:#3B3561;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border:none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-left:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3E8989;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-left: 5px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"/*Horizontal scrollbar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    padding-top: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3E8989;\n"
"    min-width: 20px;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}")
        self.result_text_browser.setObjectName("result_text_browser")
        self.gridLayout_3.addWidget(self.result_text_browser, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Speed Test"))
        self.check_button.setText(_translate("Form", "Check"))
        self.list_servers_button.setText(_translate("Form", "List Servers"))
        self.ping_button.setText(_translate("Form", "Ping"))
