# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\process_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(727, 528)
        Form.setStyleSheet("#Form {\n"
"    background-color: #A0B9D0;\n"
"}\n"
"#search_txt{\n"
"    background-color: #A0B9D0;\n"
"    border:1px solid #3E8989;\n"
"    height:30px;\n"
"    width: 245px;\n"
"    border-radius:10px;\n"
"    padding-left: 10px;\n"
"}\n"
"#topic {\n"
"    color: #3d5673;\n"
"}\n"
"QPushButton{\n"
"    width:80px;\n"
"    height:33px;\n"
"    text-align: center;\n"
"    padding: 3px;\n"
"    font-weight:bold;\n"
"    border-radius:10px;\n"
"    color: #3d5673;\n"
"    border: 1px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    background-color:#78A0BC;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.topic = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(True)
        self.topic.setFont(font)
        self.topic.setObjectName("topic")
        self.horizontalLayout.addWidget(self.topic)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_16.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.search_txt = QtWidgets.QLineEdit(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.search_txt.setFont(font)
        self.search_txt.setStyleSheet("`")
        self.search_txt.setText("")
        self.search_txt.setObjectName("search_txt")
        self.horizontalLayout_16.addWidget(self.search_txt)
        self.search_btn = QtWidgets.QPushButton(self.frame_12)
        self.search_btn.setStyleSheet("background-color: #2D728F;\n"
"width:50px;\n"
"height:25px;")
        self.search_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon)
        self.search_btn.setIconSize(QtCore.QSize(20, 20))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_16.addWidget(self.search_btn)
        self.horizontalLayout.addWidget(self.frame_12, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(Form)
        self.frame_9.setStyleSheet("#frame_9{\n"
"    background-color: #A0B9D0;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
"QHeaderView {\n"
"    background-color: #A0B9D0;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #A0B9D0;\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    border: 1px solid black;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_9)
        self.scrollArea.setStyleSheet("#scrollAreaWidgetContents{\n"
"    background-color: #A0B9D0;\n"
"}\n"
"#scrollArea{\n"
"    border: none;\n"
"}    \n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 357))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    border-radius: 15px;\n"
"    border: 1px solid #3d5673;\n"
"    background-color: #A0B9D0;\n"
"    padding:10px;\n"
"    padding-left:20px;\n"
"    gridline-color: #3d5673;\n"
"    color:#3B3561;\n"
"    font-family: \'Times New Roman\', serif;\n"
"    font-size: 15px;\n"
"}\n"
"QHeaderView {\n"
"    background-color: #A0B9D0;\n"
"    border-radius: 10px;\n"
"    color:#3B3561;\n"
"    font-family: \'Times New Roman\', serif;\n"
"    font-size: 1s5px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #A0B9D0;\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    font-family: \'Times New Roman\', serif;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #A0B9D0;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"}\n"
"QScrollArea{\n"
"    border:none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-left:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3E8989;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-left: 15px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"/*Horizontal scrollbar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    padding-top: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3E8989;\n"
"    min-width: 20px;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QTableView::item{\n"
"    padding-left: 20px;\n"
"    textAlignment: center\n"
"}\n"
"QTableView::item:selected{\n"
"    selection-background-color: #3B3561;\n"
"    selection-color: white;\n"
"}\n"
"")
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(Form)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_15.setContentsMargins(15, 10, 15, 10)
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.refresh_btn = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_15.addWidget(self.refresh_btn)
        self.kill_btn = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.kill_btn.setFont(font)
        self.kill_btn.setObjectName("kill_btn")
        self.horizontalLayout_15.addWidget(self.kill_btn)
        self.verticalLayout.addWidget(self.frame_10, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.topic.setText(_translate("Form", "Process List"))
        self.search_txt.setPlaceholderText(_translate("Form", "   Search Process"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "PID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "TTY"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "TIME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "CMD"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "ddđ"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.refresh_btn.setText(_translate("Form", "Refresh"))
        self.kill_btn.setText(_translate("Form", "Kill"))
from static import res_rc
from static import resource_rc
