# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sftp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(870, 489)
        Form.setStyleSheet("#Form{\n"
"    background-color: #A0B9D0;    \n"
"    color: #3d5673;\n"
"}\n"
"#topic{    \n"
"    color: #3d5673;\n"
"    padding-left:20px;\n"
"    padding-top:15px;\n"
"}\n"
"QPushButton{\n"
"    width:100px;\n"
"    height:33px;\n"
"    text-align: center;\n"
"    padding: 3px;\n"
"    font-weight:bold;\n"
"    border-radius:10px;\n"
"    color: #3d5673;\n"
"    border: 1px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    background-color:#78A0BC;\n"
"}\n"
"#path_label{    \n"
"    color: #3d5673;\n"
"    padding-left:20px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(20, 10, 10, 0)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        self.path_label.setFont(font)
        self.path_label.setStyleSheet("color: #3d5673")
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 4, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.send_file_btn = QtWidgets.QPushButton(self.frame)
        self.send_file_btn.setMinimumSize(QtCore.QSize(145, 39))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.send_file_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/share.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_file_btn.setIcon(icon)
        self.send_file_btn.setIconSize(QtCore.QSize(24, 24))
        self.send_file_btn.setObjectName("send_file_btn")
        self.gridLayout.addWidget(self.send_file_btn, 2, 0, 1, 1)
        self.delete_file_btn = QtWidgets.QPushButton(self.frame)
        self.delete_file_btn.setMinimumSize(QtCore.QSize(144, 39))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.delete_file_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/wifi-off.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_file_btn.setIcon(icon1)
        self.delete_file_btn.setIconSize(QtCore.QSize(24, 24))
        self.delete_file_btn.setObjectName("delete_file_btn")
        self.gridLayout.addWidget(self.delete_file_btn, 1, 1, 1, 1)
        self.new_file_btn = QtWidgets.QPushButton(self.frame)
        self.new_file_btn.setMinimumSize(QtCore.QSize(145, 39))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.new_file_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_file_btn.setIcon(icon2)
        self.new_file_btn.setIconSize(QtCore.QSize(24, 24))
        self.new_file_btn.setObjectName("new_file_btn")
        self.gridLayout.addWidget(self.new_file_btn, 1, 0, 1, 1)
        self.move_down_btn = QtWidgets.QPushButton(self.frame)
        self.move_down_btn.setMinimumSize(QtCore.QSize(144, 39))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.move_down_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.move_down_btn.setIcon(icon3)
        self.move_down_btn.setIconSize(QtCore.QSize(24, 24))
        self.move_down_btn.setObjectName("move_down_btn")
        self.gridLayout.addWidget(self.move_down_btn, 0, 1, 1, 1)
        self.move_up_btn = QtWidgets.QPushButton(self.frame)
        self.move_up_btn.setMinimumSize(QtCore.QSize(145, 39))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.move_up_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.move_up_btn.setIcon(icon4)
        self.move_up_btn.setIconSize(QtCore.QSize(24, 24))
        self.move_up_btn.setObjectName("move_up_btn")
        self.gridLayout.addWidget(self.move_up_btn, 0, 0, 1, 1)
        self.receive_file_btn = QtWidgets.QPushButton(self.frame)
        self.receive_file_btn.setMinimumSize(QtCore.QSize(144, 39))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.receive_file_btn.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.receive_file_btn.setIcon(icon5)
        self.receive_file_btn.setIconSize(QtCore.QSize(24, 24))
        self.receive_file_btn.setObjectName("receive_file_btn")
        self.gridLayout.addWidget(self.receive_file_btn, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 5, 1, 1, 1, QtCore.Qt.AlignRight)
        self.files = QtWidgets.QTreeView(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.files.setFont(font)
        self.files.setStyleSheet("QTreeWidget {\n"
"    spacing: 10px; /* Cách nhau 5px giữa các item trong 1 hàng */\n"
"}\n"
"\n"
"#files{\n"
"    background-color: #3E7CB1;\n"
"    border:1px solid #DBE4EE;\n"
"    border-radius: 25px solid #DBE4EE;\n"
"    padding:25px;\n"
"    color: #DBE4EE;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{    color: #DBE4EE;\n"
"    background-color: #3E7CB1;\n"
"    border:1px;\n"
"}\n"
"\n"
"QTreeWidget::item{\n"
"    padding-bottom:5px;        \n"
"    spacing: 10px;\n"
"}\n"
"\n"
"QTreeWidget::item::hover{\n"
"    background-color: #81A4CD;\n"
"    border:1px solid #81A4CD ;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QTreeWidget::item::pressed{\n"
"    font-weight: bold;\n"
"    padding-left:5px;\n"
"    background-color: #81A4CD;\n"
"    border:1px solid #81A4CD ;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QTreeWidget::item::selected{\n"
"    font-weight: bold;\n"
"    background-color: #81A4CD;\n"
"    border:1px solid #81A4CD ;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QTreeWidget::item::selected::active{\n"
"    background-color: #054A91;\n"
"    border:1px solid #81A4CD ;\n"
"    border-radius: 5px;\n"
"    font-weight:bold;\n"
"}\n"
"QScrollArea{\n"
"    border:none;\n"
"    padding-right:5px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #3E7CB1;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-left:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #A0B9D0;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-left: 15px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #3E7CB1;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #3E7CB1;\n"
"}\n"
"\n"
"/*Horizontal scrollbar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #3E7CB1;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    padding-top: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #A0B9D0;\n"
"    min-width: 20px;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal {\n"
"    background: #3E7CB1;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #3E7CB1;\n"
"}\n"
"")
        self.files.setObjectName("files")
        self.gridLayout_2.addWidget(self.files, 5, 0, 1, 1)
        self.topic = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(15)
        font.setBold(True)
        self.topic.setFont(font)
        self.topic.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.topic.setObjectName("topic")
        self.gridLayout_2.addWidget(self.topic, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.path_label.setText(_translate("Form", "Current Path: "))
        self.send_file_btn.setText(_translate("Form", "Send File"))
        self.delete_file_btn.setText(_translate("Form", "Disconnect "))
        self.new_file_btn.setText(_translate("Form", "Copy Path"))
        self.move_down_btn.setText(_translate("Form", "Back"))
        self.move_up_btn.setText(_translate("Form", "Home"))
        self.receive_file_btn.setText(_translate("Form", "Receive File"))
        self.topic.setText(_translate("Form", "SFTP"))
from static import res_rc
