# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sys_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(692, 530)
        Form.setStyleSheet("#Form{\n"
"    background-color: #A0B9D0;\n"
"    color: #3d5673;\n"
"}\n"
"QLabel{\n"
"    color: #3d5673;\n"
"}\n"
"#topic{\n"
"    padding-left:10px;\n"
"    padding-top:20px;\n"
"    padding-bottom:20px;    \n"
"}\n"
"#frame_7{\n"
"    background-color: #A0B9D0;\n"
"    border-radius:15px;\n"
"    padding: 5px;\n"
"    color: #3d5673;\n"
"    border: 1px solid #3d5673;\n"
"}\n"
"#scrollArea{\n"
"    padding:5px;\n"
"    background-color: #A0B9D0;\n"
"    border-radius: 15px;\n"
"    color: #3d5673;\n"
"    border: 1px solid #3d5673;\n"
"}\n"
"\n"
"#scrollAreaWidgetContents{\n"
"    background-color: #A0B9D0;\n"
"    border-radius:10px;\n"
"    \n"
"    color: #3d5673;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:3px;\n"
"    padding-bottom:3px;\n"
"    padding-right:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3E8989;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-right: 5px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #A0B9D0;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"/*Horizontal scrollbar*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    padding-top: 2px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3E8989;\n"
"    min-width: 20px;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #A0B9D0;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #A0B9D0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(25, -1, 25, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topic = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(13)
        font.setBold(True)
        self.topic.setFont(font)
        self.topic.setObjectName("topic")
        self.verticalLayout.addWidget(self.topic, 0, QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.txt_processor = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_processor.setFont(font)
        self.txt_processor.setObjectName("txt_processor")
        self.gridLayout_16.addWidget(self.txt_processor, 1, 3, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_16.addWidget(self.label_101, 3, 2, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_16.addWidget(self.label_100, 2, 2, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.gridLayout_16.addWidget(self.label_90, 2, 0, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridLayout_16.addWidget(self.label_99, 1, 2, 1, 1)
        self.txt_architecture = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_architecture.setFont(font)
        self.txt_architecture.setObjectName("txt_architecture")
        self.gridLayout_16.addWidget(self.txt_architecture, 2, 1, 1, 1)
        self.txt_platform = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_platform.setFont(font)
        self.txt_platform.setObjectName("txt_platform")
        self.gridLayout_16.addWidget(self.txt_platform, 1, 1, 1, 1)
        self.txt_sysdate = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_sysdate.setFont(font)
        self.txt_sysdate.setObjectName("txt_sysdate")
        self.gridLayout_16.addWidget(self.txt_sysdate, 3, 1, 1, 1)
        self.txt_py_version = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_py_version.setFont(font)
        self.txt_py_version.setObjectName("txt_py_version")
        self.gridLayout_16.addWidget(self.txt_py_version, 2, 3, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.gridLayout_16.addWidget(self.label_89, 1, 0, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.gridLayout_16.addWidget(self.label_91, 3, 0, 1, 1)
        self.txt_systime = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.txt_systime.setFont(font)
        self.txt_systime.setObjectName("txt_systime")
        self.gridLayout_16.addWidget(self.txt_systime, 3, 3, 1, 1)
        self.txt_hedieuhanh = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        font.setBold(True)
        self.txt_hedieuhanh.setFont(font)
        self.txt_hedieuhanh.setObjectName("txt_hedieuhanh")
        self.gridLayout_16.addWidget(self.txt_hedieuhanh, 0, 0, 1, 4)
        self.verticalLayout.addWidget(self.frame_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.topic.setText(_translate("Form", "System Information"))
        self.txt_processor.setText(_translate("Form", "N/A"))
        self.label_101.setText(_translate("Form", "System Time"))
        self.label_100.setText(_translate("Form", "Python Version"))
        self.label_90.setText(_translate("Form", "Architecture"))
        self.label_99.setText(_translate("Form", "Processor"))
        self.txt_architecture.setText(_translate("Form", "N/A"))
        self.txt_platform.setText(_translate("Form", "N/A"))
        self.txt_sysdate.setText(_translate("Form", "N/A"))
        self.txt_py_version.setText(_translate("Form", "N/A"))
        self.label_89.setText(_translate("Form", "Platform"))
        self.label_91.setText(_translate("Form", "System Date"))
        self.txt_systime.setText(_translate("Form", "N/A"))
        self.txt_hedieuhanh.setText(_translate("Form", "N/A"))
