# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 460)
        Form.setStyleSheet("#Form{\n"
"    background-color: #A0B9D0;\n"
"}\n"
"#topic{\n"
"    color: #3d5673;\n"
"    padding-left: 25px;\n"
"    padding-top: 15px;\n"
"    padding-bottom: 10px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#output_txt{\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton{\n"
"    width:100px;\n"
"    height:33px;\n"
"    text-align: center;\n"
"    padding: 3px;\n"
"    font-weight:bold;\n"
"    border-radius:10px;\n"
"    color: #3d5673;\n"
"    border: 1px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    background-color:#78A0BC;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.topic = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(15)
        font.setBold(True)
        self.topic.setFont(font)
        self.topic.setObjectName("topic")
        self.horizontalLayout_2.addWidget(self.topic)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect_button = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.connect_button_2 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.connect_button_2.setFont(font)
        self.connect_button_2.setObjectName("connect_button_2")
        self.horizontalLayout.addWidget(self.connect_button_2)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.output_txt = QtWidgets.QTextEdit(self.frame)
        self.output_txt.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.output_txt.setFont(font)
        self.output_txt.setStyleSheet("#output_txt{\n"
"    background-color:#335E81;\n"
"    color: #B0C3D7;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"    padding-top:5px;\n"
"}\n"
"QScrollArea{\n"
"    border:none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background: #335E81;\n"
"    width: 8px;\n"
"    border-radius:5px;\n"
"    padding-top:5px;\n"
"    padding-bottom:10px;\n"
"    padding-left:2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3E8989;\n"
"    min-height: 20px;\n"
"    border-radius:3px;\n"
"    padding-left: 15px\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background: #335E81;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background: #335E81;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"    background: #335E81;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #335E81;\n"
"}")
        self.output_txt.setLineWidth(1)
        self.output_txt.setObjectName("output_txt")
        self.verticalLayout_3.addWidget(self.output_txt)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("#input_txt{\n"
"    border-radius: 8px;\n"
"    background-color:#335E81;\n"
"    color: #B0C3D7;    \n"
"    padding-left: 5px;\n"
"    padding-right:5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_txt = QtWidgets.QLineEdit(self.frame_2)
        self.input_txt.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.input_txt.setFont(font)
        self.input_txt.setObjectName("input_txt")
        self.verticalLayout_2.addWidget(self.input_txt)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.topic.setText(_translate("Form", "Terminal"))
        self.connect_button.setText(_translate("Form", "Connect"))
        self.connect_button_2.setText(_translate("Form", "Disconnect"))
        self.output_txt.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.input_txt.setPlaceholderText(_translate("Form", "Command"))
